# Generated by Django 4.2.1 on 2023-06-08 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=6, verbose_name='Номер заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('order_status', models.CharField(choices=[('Принят', 'Принят'), ('Готовится', 'Готовится'), ('Отменен', 'Отменен'), ('Готов', 'Готов')], default='Принят', max_length=9, verbose_name='Статус заказа')),
                ('paid_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='InfoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField(default=0, verbose_name='Количество')),
                ('order_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Сумма')),
                ('Заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orders')),
                ('Позиция', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.positions')),
            ],
            options={
                'verbose_name': 'Информация о заказе',
                'verbose_name_plural': 'Информация о заказах',
            },
        ),
    ]
