# Generated by Django 4.2.1 on 2023-06-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoorder',
            name='servings',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Собирается', 'Собирается'), ('Принят', 'Принят'), ('Готовится', 'Готовится'), ('Отменен', 'Отменен'), ('Готов', 'Готов')], default='Собирается', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
