# Generated by Django 4.2.1 on 2023-05-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_delete_bookfeedback_delete_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoorder',
            old_name='order',
            new_name='Заказ',
        ),
        migrations.RenameField(
            model_name='infoorder',
            old_name='position',
            new_name='Позиция',
        ),
    ]
