# Generated by Django 4.2.1 on 2023-06-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_order_infoorder_заказ_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoOrder',
        ),
    ]
