# Generated by Django 4.2.1 on 2023-06-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=30, verbose_name='Электронная почта')),
                ('feedback_comment', models.TextField(verbose_name='Комментарий')),
                ('date_record', models.DateTimeField(auto_now=True, verbose_name='Дата и время отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='InfoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.orders')),
                ('Позиция', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.positions')),
            ],
            options={
                'verbose_name': 'Информация о заказе',
                'verbose_name_plural': 'Информация о заказах',
            },
        ),
    ]
