# Generated by Django 4.2.1 on 2023-06-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_bookfeedback_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoorder',
            name='order_price',
            field=models.FloatField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AddField(
            model_name='infoorder',
            name='servings',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
