# Generated by Django 4.2.1 on 2023-06-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='ФИО')),
                ('mobile_number', models.CharField(help_text='+7**********', max_length=12, verbose_name='Номер телефона')),
                ('booking_status', models.CharField(choices=[('Принят', 'Принят'), ('Подтвержден', 'Подтвержден'), ('Отменен', 'Отменен'), ('Выполнен', 'Выполнен')], default='Принят', max_length=11, verbose_name='Статус брони')),
                ('booking_comment', models.TextField(help_text='Столик: *, Количество гостей: *', max_length=255, verbose_name='Комментарий')),
                ('date_booking', models.DateTimeField(verbose_name='Дата и время брони')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации брони')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
