# Generated by Django 4.2.1 on 2023-06-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='Категория',
        ),
        migrations.AddField(
            model_name='positions',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.sections', verbose_name='Категория'),
        ),
    ]
