# Generated by Django 4.2.1 on 2023-06-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookfeedback',
            old_name='user',
            new_name='autor',
        ),
    ]
